### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': '404' is not a valid attribute name.

### ISSUE THREAD

**Issue by LaiBaoYuan** [antfu/antfu.me#67] opened 2023-09-20 09:56 UTC
### Describe the bug

托尼托尼，🥹，按照你的项目结构搭建自己的博客过程中，使用vite的pages插件，404页面使用的是`..404].md`这个文件名，为啥会出现这个问题呀
<img width="1113" alt="image" src="https://github.com/antfu/antfu.me/assets/89441249/ba7fb9cd-afdd-4304-b216-e448a672d78b">
<img width="337" alt="image" src="https://github.com/antfu/antfu.me/assets/89441249/140ce67a-132d-4a36-ad91-ee043b092445">

### Reproduction

无

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 398.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 8.7.5 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-09-20 10:02
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-20 10:02 UTC
